server:
  port: 8888
spring:
  application:
    name: donape-configservice

  cloud:
    config:
      server:
        git:
          uri: https://github.com/donaPe/donape-repoconfig.git
          default-label: main
          timeout: 10

